### ISSUE TITLE
Invalid date on author dashboard

### ISSUE THREAD

**Issue by hdrury1** [libero/reviewer#1383] opened 2020-09-09 14:08 UTC
'Invalid date' is being shown intermittently after beginning a submission in xPub then returning to it in staging.

<img width="727" alt="Screenshot 2020-09-09 at 15 08 11" src="https://user-images.githubusercontent.com/17023702/92609726-ce718980-f2ae-11ea-88ee-87371829b1e4.png">

Steps to recreate:

1. Begin a submission in xPub staging environment
2. Continue submission in Reviewer staging
3. Navigate back to the dashboard from the submission wizard
4. Observe invalid date text

The error I'm getting in the console is

```
moment.js:293 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 1599654373880, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:3368)
    at https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:23235
    at https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:23286
    at kt (https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:23580)
    at https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:23970
    at St (https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:24032)
    at Dt (https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:24064)
    at s (https://libero-reviewer--staging.elifesciences.org/static/js/0.af58abeb.chunk.js:1:203)
    at f (https://libero-reviewer--staging.elifesciences.org/static/js/8.626114b5.chunk.js:1:2098)
    at Mi (https://libero-reviewer--staging.elifesciences.org/static/js/3.f8dc6426.chunk.js:2:646775)
D @ moment.js:293
```

The date appears to show correctly upon refreshing, but the bug can be recreated by continuing the submission and navigating back to the dashboard again.

**Comment by Cooryd** [comment] 2020-09-09 14:13
Duplicate of #1379

**Closed by Cooryd** 2020-09-09 14:13 UTC
Labels: Bug
