### ISSUE TITLE
Use nginx prod config

### ISSUE THREAD

**Issue by petereast** [libero/reviewer#168] opened 2019-08-27 09:27 UTC
true, but probably the whole file would be replaced with configuration mounted as a volume?

_Originally posted by @giorgiosironi in https://github.com/libero/reviewer/pull/147_

**Comment by giorgiosironi** [comment] 2019-09-20 08:29
In the [Helm chart](https://github.com/moby/moby/issues/14080#issuecomment-484314314) we are using a forked nginx configuration, so no need to be overly production-ready in this one apart from the need to be production-like to reproduce bugs.

**Comment by erkannt** [comment] 2020-06-23 14:04
Obsolete due to use of ingress and also moving to fairly default nginx config for client.

**Closed by erkannt** 2020-06-23 14:04 UTC
Labels: Infrastructure, Tech Debt
