### ISSUE TITLE
wait for browsersession to become available on saucelabs/browserstack

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1002] opened 2020-06-04 12:57 UTC
We will always be [limited in the number of running and queued jobs](https://support.saucelabs.com/hc/en-us/articles/360047068694-Limits-on-Sauce-Connect-tunnels).

We therefore should set up our tests to wait for a connection (with a timeout?). See their [docs](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#test-on-remote-and-mobile-devices):

```js
const createTestCafe   = require('testcafe');
const testCafe         = await createTestCafe('localhost', 1337, 1338);
const runner           = testCafe.createRunner();
const remoteConnection = testcafe.createBrowserConnection();

// Visit this URL from the remote device.
console.log(remoteConnection.url);

// Wait until the remote device's browser connects.
await new Promise(resolve => remoteConnection.once('ready', resolve));
```

**Comment by norisalsaadie** [comment] 2020-06-24 14:43
This has been analysed by three people - a test repo can be found here https://github.com/libero/reviewer-client/tree/1002-saucelabs-timeout 

The runner API + Remote is powerful, but is unlikely to solve the issue. The current tool used to interact with sauce labs does have retry logic baked in - https://github.com/DevExpress/testcafe-browser-provider-saucelabs/blob/87dd75e628183630c7264c1af47e37edd6147795/src/index.js#L16

Three solutions come to mind:
1. Fork the repo/open a PR to allow the retry to be driven by an environment variable 
2. Use a tunnel and manage the connections manually
3. Can the tests be run in a serial way?

**Comment by erkannt** [comment] 2020-06-25 08:01
I can only comment on 3. right now:
- we can serialize tests in the pipeline or via changes to the makefile
- we should be able to run tests in parallel over a single tunnel

If we serialize we might have to reconsider running them on every PR as the duration will increase. The tests then need to work on non-clean state.

If we parallelize over a single tunnel the tests might need adjusting to ensure that they don't interfere with each other. Maybe random usernames (would require change to mocks container)?

**Comment by norisalsaadie** [comment] 2020-06-25 16:19
Working theory is that this was potentially caused by client side rendering and the tests proceeding without the app being ready. This has been fixed on this PR https://github.com/libero/reviewer-client/pull/307 and it seems to address the issue (thus far).

**Closed** 2020-06-25 16:28 UTC
Labels: Tech Debt, testing

**Comment by norisalsaadie** [comment] 2020-06-26 08:58
It appears there were two areas:

1. Testing the page before the DOM is ready. This is has been solved.
2. Concurrency limit as per https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/39

Waiting on a connection to be released may not be an ideal solution as CI/CD already consumes a lot of time, and potentially waiting rather than failing is worse.
